modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/TeamTwilight/berry-overgrown/issues"

[[mods]]
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/berry-overgrown"
logoFile="berry_overgrown.png"
#credits="" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

#[[mixins]]
#config="${mod_id}.mixins.json"

#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="twilightforest"
    type="required"
    versionRange="${tf_version_range}"
    ordering="AFTER"
    side="BOTH"
